networks:
  network-ead-nginx:
    name: network-ead-nginx
    driver: bridge

services:
  dashboard-ead:
    container_name: dashboard-ead
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
      - ./:/app
      - /app/node_modules
      - /app/dist
    ports:
      - '${APP_PORT:-5178}:80'
    networks:
      - network-ead-nginx
    restart: unless-stopped
    tty: true