# Etapa 1: build do projeto
FROM node:20-alpine as builder
WORKDIR /app

COPY . .
RUN npm install -g pnpm && pnpm install
RUN pnpm run build

# Etapa 2: imagem com NGINX
FROM nginx:alpine as runner

# Remove o default.conf e adiciona o nosso
COPY default.conf /etc/nginx/conf.d/default.conf

# Copia o build gerado para a pasta pública do nginx
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
