query Pergunta($id: Int!) {
  pergunta(id: $id) {
    id
    descricao
    multiEscolha
    tipo

    formularioId
    formulario {
      nome
      id
      aulaId
      subModulo {
        titulo
        id

        modulo {
          id
          titulo
        }
      }
    }

    respostas {
      descricao
      id
      perguntaId
      correta
    }
  }
}

query Perguntas(
  $filter: PerguntasFilter
  $paging: CursorPaging!
  $sorting: [PerguntasSort!]!
) {
  perguntas(filter: $filter, paging: $paging, sorting: $sorting) {
    edges {
      node {
        id
        descricao
        multiEscolha
        tipo
        formularioId
        formulario {
          nome
          id
          subModulo {
            titulo
            id
            modulo {
              id
              titulo
            }
          }
        }

        respostas {
          descricao
          id
          perguntaId
          correta
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}
